name: build, push, version Tag image

on:
  push:
    tags: "v*.*.*"
  workflow_dispatch:

env:
  IMAGE_NAME: hello-world
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Generate Git Tag
      id: generate_tag
      run: |
        az login
        VERSION_PREFIX="v"
        VERSION_MINOR="0"
        VERSION_PATCH="0"
        AzureRegistryName="imagevulacr"
        RepositoryName="hello-world"
        UPDATE_MAJOR=$(az acr repository show-tags --name $AzureRegistryName --repository $RepositoryName  --orderby time_desc --output tsv | head -n 1 | grep -oE '[0-9]+$')
        UPDATE_MAJOR=$((UPDATE_MAJOR + 1))
        NEW_TAG="${VERSION_PREFIX}${UPDATE_MAJOR}.${VERSION_MINOR}.${VERSION_MINOR}"
        echo "Generated new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Push image to registry
      run: |
        docker build -t ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.NEW_TAG }} .
        docker push --disable-content-trust ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.NEW_TAG }}
        
    # - name: Build & Push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     build-args: |
    #       version=${{ steps.tag.outputs.tag }}
    #     tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
    # 
