name: New Tag to SourceCOde
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v2
     with:
         fetch-depth: '0'
   - name: Generate Git Tag
     id: generate_tag
     run: |
       GET_TAG=$(git tag --list --sort=-version:refname | head -n 1)
       CURRENT_TAG="${GET_TAG:1}"
       IFS="." read -ra version_components <<< "$CURRENT_TAG";
       major=${version_components[0]}
       minor=${version_components[1]}
       patch=${version_components[2]:-0}
       echo "Current image version: $major.$minor.$patch"
       case ${{ github.event.inputs.version }} in
         major)
           new_tag="v$((major + 1)).$((minor)).$((patch))"
           ;;
           minor)
           new_tag="v$((major)).$((minor + 1)).$((patch))"
           ;;
           patch)
           new_tag="v$v$((major)).$((minor)).$((patch + 1))"
           ;;
         esac
       echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
   - name: Push Git Tag
     run: |
       git config user.name "GitHub Actions"
       git config user.email "github-actions@users.noreply.github.com"
       git tag $NEW_TAG
       git push origin $NEW_TAG
