name: Custom Tag Increment

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  increment_tag:
    runs-on: ubuntu-latest
    permissions:
     id-token: write #This is required for requesting the JWT
     contents: read
     pages: write
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0)"
      - name: Increment tag
        id: increment_tag
        run: echo "::set-output name=next_tag::$(python increment_tag.py ${{ steps.get_tag.outputs.tag }})"
      - name: Create new tag
        run: |
          git tag ${{ steps.increment_tag.outputs.next_tag }}
          git push origin ${{ steps.increment_tag.outputs.next_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}