name: Tag with major
on:
 push:
   branches:
     - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v2
     with:
         fetch-depth: '0'
   - name: Generate Git Tag
     id: generate_tag
     run: |
       VERSION_PREFIX="v"
       VERSION_MAJOR="1"
       UPDATE_MAJOR=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
       if [ -z "$UPDATE_MAJOR" ]; then
         UPDATE_MAJOR=1
       else
         UPDATE_MAJOR=$((UPDATE_MAJOR + 1))
       fi
       NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${UPDATE_MAJOR}"
       echo "Generated new tag: $NEW_TAG"
       echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
   - name: Push Git Tag
     run: |
       git config user.name "GitHub Actions"
       git config user.email "github-actions@users.noreply.github.com"
       git tag $NEW_TAG
       git push origin $NEW_TAG